# Generated by Django 2.2.6 on 2019-10-15 19:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('continent', models.TextField(choices=[('asia', 'Asia'), ('africa', 'Africa'), ('north America', 'North America'), ('south America', 'South America'), ('australia', 'Australia'), ('europe', 'Europe')], max_length=100)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('scholarship_availability', models.CharField(choices=[('none', 'None'), ('merit-based', 'Merit-based'), ('need-based', 'Need-based')], max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('university_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=100)),
                ('cost', models.IntegerField()),
                ('how_to_apply', models.TextField(max_length=500)),
                ('on_campus_housing', models.BooleanField(verbose_name=models.CharField(max_length=100))),
                ('campusview', models.ImageField(upload_to='upload/images/')),
                ('geolocation', django.contrib.postgres.fields.jsonb.JSONField()),
                ('application_deadline', models.DateTimeField()),
                ('logo', models.ImageField(upload_to='upload/images/')),
                ('pre_univ', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universitys', to='afro_app.User')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='universitys', to='afro_app.Country')),
                ('programs_offered', models.ManyToManyField(related_name='universitys', to='afro_app.program')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.TextField(choices=[('research scholarship', 'Research scholarship'), ('study scholarship', 'Study scholarship')], max_length=100)),
                ('study_level', models.TextField(choices=[('undergraduate', 'Undergraduate'), ('master', 'Master'), ('doctorate', 'Doctorate')], max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('application_deadline', models.DateTimeField()),
                ('logo', models.ImageField(upload_to='upload/images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='afro_app.User')),
                ('eligible_nationalities', models.ManyToManyField(related_name='scholarships', to='afro_app.Country')),
                ('programs_applicable', models.ManyToManyField(related_name='scholarships', to='afro_app.program')),
                ('university_applicable', models.ManyToManyField(related_name='scholarships', to='afro_app.University')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
