# Generated by Django 2.2.6 on 2019-10-15 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('-created',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('-created',), 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ('-created',), 'verbose_name': 'scholarship', 'verbose_name_plural': 'scholarships'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ('-created',), 'verbose_name': 'University', 'verbose_name_plural': 'universities'},
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='university',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='afro_app.Country'),
        ),
        migrations.AlterField(
            model_name='university',
            name='programs_offered',
            field=models.ManyToManyField(related_name='universities', to='afro_app.program'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
