# Generated by Django 2.2.6 on 2019-10-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro_app', '0002_auto_20191016_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='on_campus_housing',
            field=models.BooleanField(),
        ),
    ]
