# We need to use Ubuntu 16.04 (Xenial Xerus) to get Python 3.7
dist: xenial

language: python

services:
  - postgresql

addons:
  postgresql: "9.6"
  # https://gis.stackexchange.com/a/252610
  # apt:
  #   packages:
  #     - postgresql-9.6-postgis-2.3

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO_VERSION='Django>=1.8,<1.9'
  - DJANGO_VERSION='Django>=1.9,<1.10'
  - DJANGO_VERSION='Django>=1.10,<1.11'
  - DJANGO_VERSION='Django>=1.11,<2.0'
  - DJANGO_VERSION='Django>=2.0,<2.1'
  - DJANGO_VERSION='Django>=2.1,<2.2'
  - DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION='Django>=2.0,<2.1'
    - python: "2.7"
      env: DJANGO_VERSION='Django>=2.1,<2.2'
    - python: "3.4"
      env: DJANGO_VERSION='Django>=2.1,<2.2'
    - python: "2.7"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.4"
      env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
  allow_failures:
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.8,<1.9'
    - python: "3.7"
      env: DJANGO_VERSION='Django>=1.8,<1.9'
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.9,<1.10'
    - python: "3.7"
      env: DJANGO_VERSION='Django>=1.9,<1.10'
    - python: "3.6"
      env: DJANGO_VERSION='Django>=1.10,<1.11'
    - python: "3.7"
      env: DJANGO_VERSION='Django>=1.10,<1.11'
    - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'

before_install:
  # https://gis.stackexchange.com/a/252610
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get install --yes postgresql-9.6-postgis-2.4

install:
  - pip install -q $DJANGO_VERSION
  - pip install -q django-model-utils flake8 psycopg2 six swapper tox tqdm

before_script:
  # - psql -U postgres -c "CREATE EXTENSION postgis;"
  - psql -c 'create database django_cities;' -U postgres
  - psql -U postgres -c 'CREATE EXTENSION postgis;' -d django_cities

script:
  - flake8
  - PYTHONPATH=. python test_project/manage.py test test_app --noinput
